name: Expressions Practice

on:
  workflow_dispatch:

jobs:

  expressions:
    runs-on: ubuntu-latest

    steps:

      - name: Show Branch1
        run: |
          echo "Branch: ${{ github.ref_name }}"

      - name: Show Repository1
        run: |
          echo "Repository: ${{ github.repository }}"

      - name: Contains Example
        if: ${{ contains(github.ref_name, 'feature') }}
        run: |
          echo "Branch contains the word feature."

      - name: StartsWith Example
        if: ${{ startsWith(github.ref_name, 'feature/') }}
        run: |
          echo "Branch starts with feature/."