name: Issue Labeled Practice

on:
  issues:
    types:
      - labeled

jobs:
  issue-labeled:
    runs-on: ubuntu-latest

    steps:
      - name: Show Issue Information
        run: |
          echo "Alabel was added to an issue"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue User: ${{ github.event.issue.user.login }}"
          echo "Label Added: ${{ github.event.label.name }}"
          echo "Event Triggered By: ${{ github.event.sender.login }}"