name: Issue Practice

on:
  issues:
    types:
      - opened

jobs:

  issue-opened:
    runs-on: ubuntu-latest

    steps:

      - name: Show Issue Information
        run: |
          echo "A  new issue was opened"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue User: ${{ github.event.issue.user.login }}"