name: Release Published Practice

on:
  release:
    types:
      - published

jobs:
  release-test:
    runs-on: ubuntu-latest

    steps:
      - name: Release Message
        run: echo "A new release was published"

      - name: Show Release Name
        run: echo "Release Name:${{ github.event.release.name }}"

      - name: Show Release Tag
        run: echo "Release Tag:${{ github.event.release.tag_name }}"

      - name: Show Release Author
        run: echo "Release Author:${{ github.event.release.author.login }}"