name: Terraform AWS S3

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:

      # -------------------------
      # 1. Checkout
      # -------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -------------------------
      # 2. Install Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -------------------------
      # 3. Terraform Version
      # -------------------------
      - name: Terraform Version
        run: terraform version

      # -------------------------
      # 4. Terraform Init
      # -------------------------
      - name: Terraform Init
        run: terraform init

      # -------------------------
      # 5. Terraform Format Check
      # -------------------------
      - name: Terraform Format Check
        run: terraform fmt -check

      # -------------------------
      # 6. Terraform Validate
      # -------------------------
      - name: Terraform Validate
        run: terraform validate

      # -------------------------
      # 7. Terraform Plan
      # -------------------------
      - name: Terraform Plan
        run: terraform plan

      # -------------------------
      # 8. Terraform Apply
      # -------------------------
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # -------------------------
      # 9. Show Outputs
      # -------------------------
      - name: Terraform Output
        run: terraform output